### ISSUE TITLE
Update Merge package dependency to the last version

### ISSUE THREAD

**Issue by el0i404** [callumacrae/find-node-modules#16]
When running `yarn audit`

![image](https://user-images.githubusercontent.com/4323435/117285495-5fadf580-ae68-11eb-9bd9-b26c1c965bfe.png)

https://www.npmjs.com/advisories/1666

### Suggestion

Upgrade `merge` dependency to version 2.1.1 or later

**Comment by callumacrae** [comment]
done in https://github.com/callumacrae/find-node-modules/pull/15 - sorry for the delay
