### ISSUE TITLE
v1.0.2 freezes my app

### ISSUE THREAD

**Issue by kobezzza** [callumacrae/find-node-modules#3]
1.0.1 - all fine
1.0.2 - findNodeModules never returns

**Comment by CoderIvan** [comment]
+1

**Comment by callumacrae** [comment]
Broke my app, too: sorry, shouldn't have relied on the tests so much.

I've reverted the change that caused this and pushed as 1.0.3.

**Comment by callumacrae** [comment]
Fixed in https://github.com/callumacrae/find-node-modules/pull/7 as find-node-modules@1.0.4
