### ISSUE TITLE
Dependency Update: use Minmatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by zedd45** [callumacrae/find-node-modules#4]
When installing a module that uses this module as a dependency, I am getting warnings about `minmatch`: 

> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

I believe the problem lies in the dependenies of `node-findup-sync`, which is currently on [`v0.4.x`](https://github.com/js-cli/node-findup-sync/blob/master/package.json#L4) where this module currently uses [^v0.2.1](https://github.com/callumacrae/find-node-modules/blob/659662ad612f1c3aeeb95a63ba30ed0910552d47/package.json#L20)

**Comment by pkese** [comment]
@callumacrae 

There's a dependency deprecation issue here and in #5 that hadn't been resolved in a while.

Is this project abandoned?

**Comment by pkese** [comment]
Oh... sorry. I see that it is being worked on

**Comment by callumacrae** [comment]
Nope.

Updating the dependency breaks the project, and I don't know why. I haven't had the time to look into it, and nobody else has either.

**Comment by callumacrae** [comment]
Fixed in https://github.com/callumacrae/find-node-modules/pull/7 as find-node-modules@1.0.4
